// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5_y0VFcAjmIWLnnJI2aRbWGMVTKPpgE',
    appId: '1:453146987570:web:463474357b455bd6c6002b',
    messagingSenderId: '453146987570',
    projectId: 'fir-auth-tutorial-15350',
    authDomain: 'fir-auth-tutorial-15350.firebaseapp.com',
    storageBucket: 'fir-auth-tutorial-15350.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvDWW-KYjsrOLZM_0zdtuppqWjiwJ1Qk',
    appId: '1:453146987570:android:3ae1410f69190976c6002b',
    messagingSenderId: '453146987570',
    projectId: 'fir-auth-tutorial-15350',
    storageBucket: 'fir-auth-tutorial-15350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAF3FIGuoZPgCbz39QN-YO7BkDi2Fmxg0',
    appId: '1:453146987570:ios:5db06060a1c855bec6002b',
    messagingSenderId: '453146987570',
    projectId: 'fir-auth-tutorial-15350',
    storageBucket: 'fir-auth-tutorial-15350.appspot.com',
    iosClientId: '453146987570-pcliet0m96t6ttie9bl42sjc5p4t6qfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAF3FIGuoZPgCbz39QN-YO7BkDi2Fmxg0',
    appId: '1:453146987570:ios:5db06060a1c855bec6002b',
    messagingSenderId: '453146987570',
    projectId: 'fir-auth-tutorial-15350',
    storageBucket: 'fir-auth-tutorial-15350.appspot.com',
    iosClientId: '453146987570-pcliet0m96t6ttie9bl42sjc5p4t6qfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndAuthentication',
  );
}
